server:
  port: 8080

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:h2:mem:user-service-db;DB_CLOSE_DELAY=-1;
    username: admin
    password: test
    driver-class-name: org.h2.Driver
    platform: h2
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  main:
    allow-bean-definition-overriding: true
